### ISSUE TITLE
http proxy

### ISSUE THREAD

**Issue by maguowei** [maguowei/gotok8s#4]
https://docs.docker.com/config/daemon/systemd/

```
[Service]
Environment="HTTP_PROXY=http://192.168.31.52:6152" "NO_PROXY=localhost,127.0.0.1,registry.docker-cn.com"
```
```
export https_proxy=http://192.168.31.52:6152;kubeadm config images pull
```

**Comment by maguowei** [comment]
[Service]
Environment="HTTP_PROXY=http://192.168.31.52:6152" "NO_PROXY=localhost,127.0.0.1,registry.docker-cn.com"

**Comment by maguowei** [comment]
export https_proxy=http://192.168.31.52:6152;kubeadm config images pull

**Comment by maguowei** [comment]
[在中国大陆本地部署 Kubernetes 集群](https://kubethink.com/posts/create-an-on-premises-cluster-in-china-v1-12/)

**Comment by liues1992** [comment]
Docker for Mac并不使用systemd

**Comment by maguowei** [comment]
@liues1992 这里是拿linux举例，Docker for Mac 中可以直接在设置里勾选使用 `系统代理`就可以了
